BuildSystem: Mac OS X - transition to Xcode4
- transition from Xcode3 to Xcode4
- overhaul HandBrake.xcodeproj file
- simplify down to 2 configurations: debug, release
- add xcconfig for useful variants: osx106.i386, osx106.x86_64, osx107.i386, osx107.x86_64
- add configure --xcode-config as preferred method to choose OSX minimum version and SDK
- overhaul Info.plist generation to use m4 instead of cpp
- remove use of direct static libraries on command line - Xcode4 now enables -search_paths_first by default
- reference external build static libraries project file - greatly simplifying project file maintenance
- update universal build targets to use --xcode-config
- update ffmpeg hack to build on i386 in both debug and optimized modes
- update ffmpeg build to show compile verbosity
- enable local yasm when yasm probe fails
- remove unused GCC.ldsysroot
- remove unused GCC.ldminver
- enhance xcodemake to use --sysroot, --minver
- update/regenerate docs accordingly
- add support for configure-time repo probe when svn repo is incompatible format to Xcode via .svn/HANDBRAKE_REPO_PROBE
- replaced make/test/build.matrix.darwin with make/test/build.matrix


git-svn-id: svn://svn.handbrake.fr/HandBrake/trunk@4395 b64f7644-9d1e-0410-96f1-a4d463321fa5

diff --git a/make/xcodemake b/make/xcodemake
--- a/make/xcodemake
+++ b/make/xcodemake
@@ -3,68 +3,74 @@
 
 set -e
 
-## This script is invoked by Xcode external targets.
+## This script is initiated by either xcodebuild or Xcode.app.
 ##
-## We must guarantee no jobserver is passed through since the file-descriptors
-## have been clobbered by Xcode. If this is not done then make behaves as if
-## it is allowed to run an infinite number of jobs.
+## We must guarantee no jobserver is passed through since file-descriptors are
+## clobbered by Xcode. If this is not done then make allows unlimited jobs.
 ##
 MAKEFLAGS=
 MFLAGS=
 
-## sanity check - the build system only supports 1 arch at a time
+## validate environment
+case "$EXTERNAL_DRIVER" in
+bootstrap) ;; ## bootstrapping from terminal
+terminal)  ;; ## building from terminal
+xcode)     ;; ## building from Xcode.app
+*)
+    echo "ERROR: unexpected value for EXTERNAL_DRIVER: $EXTERNAL_DRIVER"
+    exit 1
+    ;;
+esac
+
+## validate environment
+for name in EXTERNAL_BUILD EXTERNAL_JOBS EXTERNAL_SRC; do
+    eval v="\$$name"
+    if [ -z "$v" ]; then
+        echo "ERROR: missing value for $name"
+        exit 1
+    fi
+done
+
+## validate environment
 archcount=`echo $ARCHS | awk '{ print NF }'`
 if [ "$archcount" -ne 1 ]; then
     echo "*********************************************************************"
     echo "***"
-    echo "*** ERROR: invalid number of architectures: $ARCHS"
-    echo "*** This build system builds one (1) archtecture at a time."
+    echo "*** ERROR: multiple architectures: $ARCHS"
+    echo "***"
+    echo "*** This build system does not support more than one (1)"
+    echo "*** simultaneous architecture setting."
     echo "***"
     echo "*********************************************************************"
     exit 1
 fi
 
-## compute if re/configure necessary
-if [ $EXTERNAL_METHOD != 'xcode' ]; then
-    reconfigure="terminal -> Xcode"
-elif [ ! -f $EXTERNAL_BUILD/GNUmakefile ]; then
-    reconfigure="no configuration present"
-elif [ $EXTERNAL_SRC/make/configure.py -nt $EXTERNAL_BUILD/GNUmakefile ]; then
-    reconfigure="configure script was updated"
-else
-    reconfigure=
-fi
-
-## perform re/configure
-if [ -n "$reconfigure" ]; then
-    echo "reconfiguring ($reconfigure)"
-
-    case "$CONFIGURATION" in
-    debug*)
-        debug="--debug=max --optimize=none"
-        ;;
-    standard*|*)
-        debug=
-        ;;
-    esac
-
-    ## invoke configure with (hidden) option which indicates conf performed by xcode
-    (set -x; $EXTERNAL_SRC/configure --force $EXTERNAL_CONFARGS \
-        --build=$EXTERNAL_BUILD --arch=$ARCHS $debug --conf-method=xcode PATH=$PATH )
-fi
+exit_post_log=0
 
 ## compute goals; these correlate with TARGET_NAME and ACTION from Xcode
 spec="$TARGET_NAME:$ACTION"
-echo "env specification: $spec"
+echo "target specification: $spec"
 case "$spec" in
-    contrib:clean)
-        goals=contrib.xclean
-        ;;
-    contrib:*)
-        goals=contrib.install
-        ;;
     external:clean)
-        goals=clean
+        if [ "$EXTERNAL_DRIVER" == "xcode" ]; then
+            ## driving build from Xcode.app do pristine clean
+            if [ -z "$EXTERNAL_BUILD" ]; then
+                echo "ERROR: unsafe rm -fr would result because EXTERNAL_BUILD is not defined"
+                exit 1
+            fi
+            if [ -d "$EXTERNAL_BUILD" ]; then
+                cmd="/bin/rm -fr $EXTERNAL_BUILD/*"
+                echo "$cmd"
+                $cmd
+                [ $? -ne 0 ] && exit 1
+                exit_post_log=1
+            else
+                echo "already clean"
+            fi
+        else
+            ## driving build from xcodebuild do xclean, preserving configuration
+            goals=xclean
+        fi
         ;;
     external:*)
         if [ -z "$EXTERNAL_GOALS" ]; then
@@ -73,23 +79,81 @@ case "$spec" in
             goals="$EXTERNAL_GOALS"
         fi
         ;;
-    libhb:clean)
-        goals=libhb.clean
-        ;;
-    libhb:*)
-        goals=libhb.build
-        ;;
     *)
-        echo "ERROR: invalid env specification: $spec"
+        echo "ERROR: unexpected env specification: $spec"
         exit 1
         ;;
 esac
 
-## safeguard against passing blank value which would result in unlimited jobs
-if [ -z "$EXTERNAL_JOBS" ]; then
-    jobs=
+## compute if re/configure necessary
+if [ ! -f $EXTERNAL_BUILD/GNUmakefile ]; then
+    reconfigure="no configuration present"
+elif [ $EXTERNAL_SRC/make/configure.py -nt $EXTERNAL_BUILD/GNUmakefile ]; then
+    reconfigure="configure script was updated"
+elif [ $EXTERNAL_DRIVER == "bootstrap" ]; then
+    reconfigure="driver bootstrap"
 else
-    jobs=--jobs=$EXTERNAL_JOBS
+    reconfigure=
+fi
+
+## perform re/configure
+if [ -n "$reconfigure" ]; then
+    echo "reconfiguring ($reconfigure)"
+
+    if [ "$EXTERNAL_DRIVER" == "bootstrap" ]; then
+        driver="--xcode-driver=terminal"
+    else
+        driver="--xcode-driver=$EXTERNAL_DRIVER"
+    fi
+
+    case "$GCC_VERSION" in
+    com.apple.compilers.llvmgcc42)
+        gcc="--gcc=$DEVELOPER_BIN_DIR/llvm-gcc-4.2"
+        ;;
+    com.apple.compilers.llvm.clang.1_0)
+        gcc="--gcc=$DEVELOPER_BIN_DIR/clang"
+        ;;
+    *)
+        gcc=
+        ;;
+    esac
+
+    if [ -n "$ARCHS" ]; then
+        arch="--arch=$ARCHS"
+    else
+        arch=
+    fi
+
+    case "$CONFIGURATION" in
+    debug*)
+        debug="--debug=max --optimize=none"
+        ;;
+    release*|*)
+        debug=
+        ;;
+    esac
+
+    if [ -n "$SDKROOT" ]; then
+        sysroot="--sysroot=$SDKROOT"
+    else
+        sysroot=
+    fi
+
+    if [ -n "$MACOSX_DEPLOYMENT_TARGET" ]; then
+        minver="--minver=$MACOSX_DEPLOYMENT_TARGET"
+    else
+        minver=
+    fi
+
+    ## invoke configure with (hidden) option which indicates conf performed by xcode
+    (set -ex; $EXTERNAL_SRC/configure --force \
+        $EXTERNAL_CONF_ARGS \
+        --build="$EXTERNAL_BUILD" \
+        $driver \
+        --xcode-symroot="$SYMROOT" \
+        --xcode-config="$EXTERNAL_XCCONFIG" \
+        $gcc $arch $debug $sysroot $minver)
+    [ $? -ne 0 ] && exit 1
 fi
 
 ## log environment as provided by Xcode
@@ -99,7 +163,18 @@ if [ ! -d $logdir ]; then
 fi
 env | sort > $logdir/xcodemake.env.txt
 
+[ $exit_post_log -ne 0 ] && exit 0
+
+## safeguard against passing blank value which would result in unlimited jobs
+if [ -z "$EXTERNAL_JOBS" ]; then
+    jobs=
+elif [ "$EXTERNAL_JOBS" == "auto" ]; then
+    jobs=--jobs=`sysctl -n hw.activecpu`
+else
+    jobs=--jobs=$EXTERNAL_JOBS
+fi
+
 ## pull the trigger
-## must set BUILD.method != terminal to prevent inifinite recursion
+## must set XCODE.driver to prevent inifinite recursion
 set -x
-exec make -C $EXTERNAL_BUILD BUILD.method=xcode $jobs $goals $EXTERNAL_VARS
+exec make -C $EXTERNAL_BUILD XCODE.driver=xcodemake $jobs $goals $EXTERNAL_VARS
