BuildSystem: darwin - made Xcode external targets consistent for each configuration. - shunted terminal NAME=VALUE vars through xcodebuild. - folded macosx/module.xcode shunt functions into single. - added new report target to show a single var; eg: make report.var NAME=GCC.gcc .
BuildSystem: darwin ppc
- fixed configure on ppc host: correctly identify native architecture.
- fixed configure to be more resilient when svn probes fail.
- fixed configure to show error output for svn probes.

BuildSystme: xcode
- added external target 'external' to represent 'all things in external system'
  which is slight more than what 'libhb' might represent.
- added doc section Building.osx: External Targets .


git-svn-id: svn://svn.handbrake.fr/HandBrake/trunk@2214 b64f7644-9d1e-0410-96f1-a4d463321fa5

diff --git a/make/xcodemake b/make/xcodemake
--- a/make/xcodemake
+++ b/make/xcodemake
@@ -1,5 +1,7 @@
-#!/bin/sh -ex
+#!/bin/sh
 #
+
+set -e
 
 ## This script is invoked by Xcode external targets.
 ##
@@ -8,6 +10,7 @@
 ## it is allowed to run an infinite number of jobs.
 ##
 MAKEFLAGS=
+MFLAGS=
 
 cd $EXTERNAL_BUILD
 
@@ -43,33 +46,40 @@ else
     jobs=--jobs=$EXTERNAL_JOBS
 fi
 
-## compute target
-case "$1:$2" in
-contrib:clean)
-    target=contrib.xclean
-    ;;
-contrib:*)
-    target=contrib.install
-    ;;
-*:clean)
-    target=clean
-    ;;
-libhb:'')
-    if [ -z "$EXTERNAL_GOALS" ]; then
-        target=build
-    else
-        target="$EXTERNAL_GOALS"
-    fi
-    ;;
-*:'')
-    target=build
-    ;;
-*)
-    echo "usage: $0 PRODUCT ACTION"
-    exit 1
-    ;;
+spec="$TARGET_NAME:$ACTION"
+echo "env specification: $spec"
+
+## compute goals
+case "$spec" in
+    contrib:clean)
+        goals=contrib.xclean
+        ;;
+    contrib:*)
+        goals=contrib.install
+        ;;
+    external:clean)
+        goals=clean
+        ;;
+    external:*)
+        if [ -z "$EXTERNAL_GOALS" ]; then
+            goals=build
+        else
+            goals="$EXTERNAL_GOALS"
+        fi
+        vars="$EXTERNAL_VARS"
+        ;;
+    libhb:clean)
+        goals=libhb.clean
+        ;;
+    libhb:*)
+        goals=libhb.build
+        ;;
+    *)
+        echo "ERROR: invalid env specification: $spec"
+        exit 1
+        ;;
 esac
 
 ## handoff
 set -x
-exec make -C $EXTERNAL_BUILD BUILD.method=xcode $jobs $target
+make -C $EXTERNAL_BUILD BUILD.method=xcode $jobs $goals $vars
